
services:

  # -------------------- INFRA --------------------

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  # -------------------- EUREKA --------------------

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  # -------------------- API GATEWAY --------------------

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8765:8765"
    env_file:
      - ".env"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server

  # -------------------- AUTH SERVICE --------------------

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    env_file:
      - ".env"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
      - mongodb

  # -------------------- BOOKING SERVICE --------------------

  booking-service:
    build: ./booking-service
    container_name: booking-service
    ports:
      - "8084:8084"
    env_file:
      - ".env"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
      - mongodb
      - rabbitmq

  # -------------------- ASSIGNMENT SERVICE --------------------

  assignment-service:
    build: ./assignment-service
    container_name: assignment-service
    ports:
      - "8085:8085"
    env_file:
      - ".env"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
      - mongodb
      - rabbitmq
      - booking-service
      - technician-service

  # -------------------- SERVICE MANAGEMENT --------------------

  service-management-service:
    build: ./service-management-service
    container_name: service-management-service
    ports:
      - "8082:8082"
    env_file:
      - ".env"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
      - mongodb

  # -------------------- TECHNICIAN SERVICE --------------------

  technician-service:
    build: ./technician-service
    container_name: technician-service
    ports:
      - "8083:8083"
    env_file:
      - ".env"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
      - mongodb

  # -------------------- NOTIFICATION SERVICE --------------------

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8086:8086"
    env_file:
      - ".env"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - rabbitmq
      - auth-service

# -------------------- VOLUMES --------------------

volumes:
  mongo_data:
